#include "isp_file.h"

#include <glib.h>
#include <glib/gstdio.h>

const char* isp_file_path() {
    const char* env = g_getenv("CAMERA_STREAMER_ISP_FILE");
    return env != nullptr && *env != '\0'
               ? env
               : "/var/nvidia/nvcam/settings/camera_overrides.isp";
}

std::string isp_file_content(const TuningConfig& tuning) {
    char* s = g_strdup_printf(
        "# Generated by camera-streamer (set-tuning / [tuning] config).\n"
        "# Manual edits are overwritten. Bake changed defaults into\n"
        "# yocto/meta-vc-camera/recipes-bsp/isp-tuning/ and the [tuning]\n"
        "# defaults together.\n"
        "\n"
        "# Sensor optical-black pedestal (10-bit units). Wrong values show\n"
        "# as a color haze over the whole image (unsubtracted offset).\n"
        "opticalBlack.manualBiasR   = %d;\n"
        "opticalBlack.manualBiasGR  = %d;\n"
        "opticalBlack.manualBiasGB  = %d;\n"
        "opticalBlack.manualBiasB   = %d;\n"
        "opticalBlack.float.manualBiasR  = %.8f;\n"
        "opticalBlack.float.manualBiasGR = %.8f;\n"
        "opticalBlack.float.manualBiasGB = %.8f;\n"
        "opticalBlack.float.manualBiasB  = %.8f;\n"
        "\n"
        "# Post-AWB white trim (diagonal CCM): neutralizes a systematic\n"
        "# white-balance bias. Replace with a full ColorChecker matrix\n"
        "# when available (tools/isp-tuning).\n"
        "colorCorrection.srgbMatrix[0]\t = {%.8f, 0.00000000, 0.00000000};\n"
        "colorCorrection.srgbMatrix[1]\t = {0.00000000, 1.00000000, 0.00000000};\n"
        "colorCorrection.srgbMatrix[2]\t = {0.00000000, 0.00000000, %.8f};\n",
        tuning.black_level, tuning.black_level, tuning.black_level,
        tuning.black_level, tuning.black_level / 1023.0,
        tuning.black_level / 1023.0, tuning.black_level / 1023.0,
        tuning.black_level / 1023.0, tuning.wb_trim_r, tuning.wb_trim_b);
    std::string out(s);
    g_free(s);
    return out;
}

bool isp_file_sync(const TuningConfig& tuning) {
    const char* path = isp_file_path();
    const std::string content = isp_file_content(tuning);

    gchar* current = nullptr;
    if (g_file_get_contents(path, &current, nullptr, nullptr)) {
        const bool same = content == current;
        g_free(current);
        if (same)
            return false;
    }

    GError* err = nullptr;
    if (!g_file_set_contents(path, content.c_str(), content.size(), &err)) {
        g_warning("tuning: cannot write %s: %s", path, err->message);
        g_error_free(err);
        return false;
    }
    g_chmod(path, 0664);  // Argus silently ignores the file on wrong modes
    g_message("tuning: wrote %s (black=%d trim R %.4f B %.4f)", path,
              tuning.black_level, tuning.wb_trim_r, tuning.wb_trim_b);
    return true;
}
